[profile]
name = "test"
application = "terminal"

[jog]
positive = ["right"]
negative = ["left"]

[shuttle]
positive = ["l"]
negative = ["j"]
neutral = ["k"]
rates_per_second = [0, 1, 2, 3, 4, 5, 6, 7]

[buttons.1]
press = ["1"]

[buttons.2]
press = ["2"]

[buttons.3]
press = ["3"]

[buttons.4]
press = ["4"]

[buttons.5]
press = ["5"]

[buttons.6]
press = ["6"]

[buttons.7]
press = ["7"]

[buttons.8]
press = ["8"]

[buttons.9]
press = ["9"]

[buttons.10]
press = ["0"]

